const SET_CAROUSEL = "SET_CAROUSEL";
const SET_MOVIELIST = "SET_MOVIELIST";

// quanr lý phim
const SET_PHIMDANGCHIEU = "SET_PHIMDANGCHIEU";
const SET_PHIMSAPCHIEU = "SET_PHIMSAPCHIEU";

export { SET_CAROUSEL, SET_MOVIELIST,SET_PHIMDANGCHIEU,SET_PHIMSAPCHIEU };
