const SET_CAROUSEL = "SET_CAROUSEL";
const SET_MOVIELIST = "SET_MOVIELIST";

// quanr lý phim
const SET_PHIMDANGCHIEU = "SET_PHIMDANGCHIEU";
const SET_PHIMSAPCHIEU = "SET_PHIMSAPCHIEU";
const ALL_PHIM = "ALL_PHIM";

// quan ly rap
const SET_MOVIETHEATER = "SET_MOVIETHEATER";
const SET_INFOTHEATER = "SET_INFOTHEATER";
const SET_CHEDULEMOVIE = "SET_CHEDULEMOVIE";

// Quan ly nguoi dung
const SET_ACCOUNTS_USER = "SET_ACCOUNTS_USER";

// Quan ly dat ve
const SET_BOOKING_MOVIE = "SET_BOOKING_MOVIE";
const SET_SEAT_BOOKED = "SET_SEAT_BOOKED";
// LocalStorage
const USER_ACCOUNT_KEY = "USER_ACCOUNT_KEY";
export {
  SET_CAROUSEL,
  SET_MOVIELIST,
  SET_PHIMDANGCHIEU,
  SET_PHIMSAPCHIEU,
  ALL_PHIM,
  SET_MOVIETHEATER,
  SET_INFOTHEATER,
  SET_CHEDULEMOVIE,
  SET_ACCOUNTS_USER,
  USER_ACCOUNT_KEY,
  SET_BOOKING_MOVIE,
  SET_SEAT_BOOKED
};
